# Generated by Django 4.0 on 2022-04-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receipient',
            new_name='recipient',
        ),
    ]
